### ISSUE TITLE
Creating official Debian packages would be much easier when

### ISSUE THREAD

**Issue by alexmyczko** [MEPP-team/MEPP2#38]
you could look for system eigen3 and CImg instead of shipping them in External, would also improve build time. Would you consider such change?

reference: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013111

**Comment by elombardi2** [comment]
We provide CImg in the External directory for portability and consistency across the
supported OSs (Linux, Windows, MacOS). This choice has no impact on build
time because CImg is a header only library. By the way the Debian packaged version 
of CImg comes with no precompiled library. So CImg code would in any case be compiled
during MEPP2 compilation.

Please note that Eigen is not shipped with the MEPP2 project. The system package is used.

**Comment by alexmyczko** [comment]
Thank you for the quick explanation and sorry I did not check in detail myself yet...
